name: Build Cordova APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Cordova and cordova-res
      run: |
        npm install -g cordova
        npm install -g cordova-res

    - name: Install project dependencies
      run: npm install

    - name: Add Android platform
      run: cordova platform add android

    - name: Generate Android icons from logo.png
      run: cordova-res android --skip-config --copy

    - name: Build APK
      run: cordova build android

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: apk-build-artifact
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
